#! /usr/bin/env python2
import sys
import os

sys.path.append("/usr/local/lib/python2.7/site-packages")

from fireconf import fire, config

config_path = os.path.expanduser("~/.config/firerc")

def check_default_path():
    is_file = os.path.isfile(config_path);
    if not is_file:
        print   "Default config file does not exist " \
                "and none has been specified. Exiting."
        sys.exit(0)


if __name__ == "__main__":

    if len(sys.argv) == 1:
        check_default_path()

    elif len(sys.argv) == 2:
        new_path = os.path.expanduser(sys.argv[1])
        is_file = os.path.isfile(new_path)
        if not is_file:
            print   "The specified file doesn't exist" \
                    " or is a directory." \
                    " Using default config file."
            check_default_path()

        else:
            config_path = new_path

    else:
        print "Usage: ./fsm [config file]"
        sys.exit(0)

    fire.run(config_path)
